import random


def run_bilingual_quiz(fragen, titel_en, titel_de):
    """
    Führt ein zweisprachiges Multiple-Choice-Quiz durch (Englisch und Deutsch).
    """
    falsche_antworten = 0
    gesamt_fragen = len(fragen)
    # Mapping für die Antworten des Benutzers (A=0, B=1, C=2, D=3)
    antwort_mapping = {'A': 0, 'B': 1, 'C': 2, 'D': 3}
    optionen_labels = ['A', 'B', 'C', 'D']

    print(f"=== {titel_en} / {titel_de} ({gesamt_fragen} Questions/Fragen) ===")
    print(
        "Please enter the correct answer (A, B, C, or D). / Bitte geben Sie die korrekte Antwort (A, B, C oder D) ein.")
    print("-" * 80)

    for i, (frage_en, frage_de, optionen_en, optionen_de, korrekter_index) in enumerate(fragen, 1):

        # Zeigt nur die tatsächlich vorhandenen Optionen an
        aktuelle_labels = optionen_labels[:len(optionen_en)]

        print(f"\n--- Question/Frage {i} ---")

        # ENGLISCHER BLOCK
        print(f"\n[ENGLISH ORIGINAL]")
        print(f"{i}) {frage_en}")
        for label, option in zip(aktuelle_labels, optionen_en):
            print(f"  {label}. {option}")

        # DEUTSCHER BLOCK
        print(f"\n[DEUTSCHE ÜBERSETZUNG]")
        print(f"{i}) {frage_de}")
        for label, option in zip(aktuelle_labels, optionen_de):
            print(f"  {label}. {option}")

        while True:
            benutzer_eingabe = input("\nYour Answer (A, B, C, D): ").strip().upper()

            # Überprüft, ob die Eingabe gültig ist
            if benutzer_eingabe in aktuelle_labels:
                benutzer_index = antwort_mapping[benutzer_eingabe]
                break
            else:
                print(f"Invalid input. Please enter {', '.join(aktuelle_labels)}.")

        # Antwort prüfen
        if benutzer_index == korrekter_index:
            print("✅ Correct! / Korrekt!")
        else:
            falsche_antworten += 1
            korrekte_antwort_label = optionen_labels[korrekter_index]
            # Sicherstellen, dass der Index nicht außerhalb der Bounds liegt
            korrekte_antwort_text_en = optionen_en[korrekter_index] if korrekter_index < len(optionen_en) else "Unknown"
            print(f"❌ Wrong. The correct answer is **{korrekte_antwort_label}**: {korrekte_antwort_text_en}")
            print(f"❌ Falsch. Die richtige Antwort ist **{korrekte_antwort_label}**.")

        print("-" * 80)

    # Zusammenfassung
    print(f"\n=== {titel_en} / {titel_de} Quiz Finished ===")
    richtige_antworten = gesamt_fragen - falsche_antworten
    print(f"Result: {richtige_antworten} out of {gesamt_fragen} questions answered correctly.")

    # Passing score for CDL General Knowledge is 80% (102/127 for this full set)
    required_to_pass = int(gesamt_fragen * 0.80)
    print(f"Ergebnis: {richtige_antworten} von {gesamt_fragen} Fragen richtig beantwortet.")
    if richtige_antworten / gesamt_fragen >= 0.8:
        print(f"🎉 **PASS!** (You needed {required_to_pass}/{gesamt_fragen} correct answers) / **BESTANDEN!**")
    else:
        print(
            f"😢 **FAIL.** You need {required_to_pass}/{gesamt_fragen} to pass. Keep practicing. / **NICHT BESTANDEN.**")


# --- CDL General Knowledge Test Fragen (127 Fragen) ---
# Format: (Fragentext EN, Fragentext DE, [Optionen EN], [Optionen DE], Korrekte Antwort-Index (0=A, 1=B, 2=C, 3=D))
quiz_fragen_general_knowledge = [
    ("1) You will lose your CDL for one year if :", "1) Sie verlieren Ihren CDL für ein Jahr, wenn:",
     ["You drive a commercial motor vehicle under the influence of alcohol or drugs.",
      "You leave the scene of an accident involving a commercial motor vehicle you were driving.",
      "You used a commercial motor vehicle to commit a felony.", "All of the above."],
     ["Sie ein Nutzfahrzeug unter dem Einfluss von Alkohol oder Drogen fahren.",
      "Sie den Unfallort eines Unfalls mit einem von Ihnen gefahrenen Nutzfahrzeug verlassen.",
      "Sie ein Nutzfahrzeug zur Begehung eines Verbrechens genutzt haben.", "Alle der oben genannten."], 3),
    ("2) You could lose your CDL for life if:", "2) Sie könnten Ihren CDL lebenslang verlieren, wenn:",
     ["You try to keep more than one CDL license.", "You are involved in a fatal accident.",
      "You are convicted of a felony involving drugs.", "None of the above can cause loss of license for life."],
     ["Sie versuchen, mehr als eine CDL-Lizenz zu besitzen.", "Sie in einen tödlichen Unfall verwickelt sind.",
      "Sie wegen eines Verbrechens im Zusammenhang mit Drogen verurteilt werden.",
      "Keines der oben genannten kann zum lebenslangen Verlust der Lizenz führen."], 2),
    ("3) The new BAC (Blood Alcohol Concentration) level is:",
     "3) Der neue BAK (Blutalkoholkonzentration) Grenzwert ist:", [".10", ".07", ".04", ".05"],
     [".10", ".07", ".04", ".05"], 2),
    ("4) The driver's vehicle inspection report must be filled out:",
     "4) Der Inspektionsbericht des Fahrers muss ausgefüllt werden:",
     ["At the beginning of the trip.", "1/2 way through the trip.", "The following morning.",
      "At the end of the trip."],
     ["Am Anfang der Fahrt.", "Auf halber Strecke der Fahrt.", "Am folgenden Morgen.", "Am Ende der Fahrt."], 0),
    ("5) You are checking your tires for a pre-trip inspection. Which of these statements is true?",
     "5) Sie überprüfen Ihre Reifen für eine Inspektion vor der Fahrt. Welche dieser Aussagen ist wahr?",
     ["Dual tires should be touching each other.",
      "Radial and bias-ply tires can be used together on the same vehicle.",
      "2/32 inch tread depth is safe for the front tires.",
      "Tires of mismatched size should not be used on the same vehicle."], ["Zwillingsreifen sollten sich berühren.",
                                                                            "Radial- und Diagonalreifen können zusammen am selben Fahrzeug verwendet werden.",
                                                                            "2/32 Zoll Profiltiefe ist sicher für die Vorderreifen.",
                                                                            "Reifen unterschiedlicher Größe sollten nicht am selben Fahrzeug verwendet werden."],
     3),
    ("6) You are checking your wheels and rims for a pre-trip inspection. Which of these statements is true?",
     "6) Sie überprüfen Ihre Räder und Felgen für eine Inspektion vor der Fahrt. Welche dieser Aussagen ist wahr?",
     ["Rust around wheel nuts may mean they are loose.", "Cracked wheels or rims can be used if they have been welded.",
      "A missing clamp is acceptable if the other clamps are tight.", "All of the above are true."],
     ["Rost um Radmuttern kann bedeuten, dass sie locker sind.",
      "Gerissene Räder oder Felgen können verwendet werden, wenn sie geschweißt wurden.",
      "Eine fehlende Klammer ist akzeptabel, wenn die anderen Klammern fest sind.",
      "Alle der oben genannten sind wahr."], 0),
    ("7) Which of these statements about checking mirrors is true?",
     "7) Welche dieser Aussagen über das Überprüfen von Spiegeln ist wahr?",
     ["You should check your mirrors twice for a lane change.",
      "You should check your mirrors to watch for hazards to the side.",
      "You should check your mirrors to keep an eye on your tires.", "All of the above are true."],
     ["Sie sollten Ihre Spiegel zweimal für einen Spurwechsel überprüfen.",
      "Sie sollten Ihre Spiegel überprüfen, um auf Gefahren an der Seite zu achten.",
      "Sie sollten Ihre Spiegel überprüfen, um Ihre Reifen im Auge zu behalten.", "Alle der oben genannten sind wahr."],
     3),
    ("8) Which of these statements about the pre-trip inspection is true?",
     "8) Welche dieser Aussagen über die Inspektion vor der Fahrt ist wahr?",
     ["If you find a broken part, you should fix it before driving.",
      "You should inspect your vehicle before and after each trip.",
      "You should inspect the brake drums after a long downhill drive.", "All of the above are true."],
     ["Wenn Sie ein defektes Teil finden, sollten Sie es vor der Fahrt reparieren.",
      "Sie sollten Ihr Fahrzeug vor und nach jeder Fahrt inspizieren.",
      "Sie sollten die Bremstrommeln nach einer langen Bergabfahrt inspizieren.", "Alle der oben genannten sind wahr."],
     3),
    ("9) Which of these statements about causes of vehicle fires is true?",
     "9) Welche dieser Aussagen über Ursachen von Fahrzeugbränden ist wahr?",
     ["Poor ventilation of the engine can cause fire.", "Low tire pressure is a common cause of tire fires.",
      "When the engine is hot, you should keep the hood tightly closed.", "All of the above are true."],
     ["Schlechte Belüftung des Motors kann Feuer verursachen.",
      "Niedriger Reifendruck ist eine häufige Ursache für Reifenbrände.",
      "Wenn der Motor heiß ist, sollten Sie die Motorhaube fest geschlossen halten.",
      "Alle der oben genannten sind wahr."], 1),
    ("10) You are driving a new truck with a manual transmission. What gear should you use to take a long downhill grade?",
     "10) Sie fahren einen neuen LKW mit Schaltgetriebe. Welchen Gang sollten Sie für eine lange Bergabfahrt verwenden?",
     ["The same gear you would use to climb the hill.", "One gear higher than the one you would use to climb the hill.",
      "A lower gear than the one you would use to climb the hill."],
     ["Denselben Gang, den Sie für die Bergauffahrt verwenden würden.",
      "Einen Gang höher als den, den Sie für die Bergauffahrt verwenden würden.",
      "Einen niedrigeren Gang als den, den Sie für die Bergauffahrt verwenden würden."], 2),
    ("11) Controlled braking is:", "11) Kontrolliertes Bremsen ist:",
     ["Applying the brakes as hard as possible without locking the wheels.",
      "Applying the brakes with maximum force and releasing as soon as the wheels lock up.",
      "Used to keep your vehicle in a straight line when braking.", "Both A and C."],
     ["Bremsen so stark wie möglich, ohne die Räder zu blockieren.",
      "Bremsen mit maximaler Kraft und Loslassen, sobald die Räder blockieren.",
      "Wird verwendet, um Ihr Fahrzeug beim Bremsen in einer geraden Linie zu halten.", "Sowohl A als auch C."], 3),
    ("12) When driving a commercial motor vehicle, you must inspect your tires every time you stop. Which of these statements is true?",
     "12) Wenn Sie ein Nutzfahrzeug fahren, müssen Sie Ihre Reifen jedes Mal überprüfen, wenn Sie anhalten. Welche dieser Aussagen ist wahr?",
     ["Tires should be hot to the touch.", "Tires that have been sitting in the sun will be warmer than the others.",
      "Radial and bias-ply tires may be used together on the same axle.", "All of the above are true."],
     ["Reifen sollten sich heiß anfühlen.", "Reifen, die in der Sonne standen, sind wärmer als die anderen.",
      "Radial- und Diagonalreifen dürfen an derselben Achse zusammen verwendet werden.",
      "Alle der oben genannten sind wahr."], 1),
    ("13) You are checking your steering and exhaust systems during a pre-trip inspection. Which of these is true?",
     "13) Sie überprüfen Ihre Lenk- und Abgassysteme während einer Inspektion vor der Fahrt. Welche dieser Aussagen ist wahr?",
     ["The steering wheel should not have more than 10 degrees or about 2 inches of play on a 20 inch steering wheel.",
      "Leaking joints in the exhaust system should be ignored.", "All of the above are true."],
     ["Das Lenkrad sollte nicht mehr als 10 Grad oder etwa 2 Zoll Spiel bei einem 20-Zoll-Lenkrad haben.",
      "Undichte Stellen im Abgassystem sollten ignoriert werden.", "Alle der oben genannten sind wahr."], 2),
    ("14) Which of these statements is true about notifying your employer about a license suspension?",
     "14) Welche dieser Aussagen ist wahr über die Benachrichtigung Ihres Arbeitgebers über einen Führerscheinentzug?",
     ["If you are convicted of any traffic violations, you must notify your employer within 30 days.",
      "If your license is suspended, you do not need to notify your employer, just the State.",
      "You must notify your employer before the end of the next business day if your license is suspended.",
      "All of the above are true."],
     ["Wenn Sie wegen Verkehrsverstößen verurteilt werden, müssen Sie Ihren Arbeitgeber innerhalb von 30 Tagen benachrichtigen.",
      "Wenn Ihre Lizenz entzogen wird, müssen Sie Ihren Arbeitgeber nicht benachrichtigen, nur den Staat.",
      "Sie müssen Ihren Arbeitgeber vor dem Ende des nächsten Geschäftstages benachrichtigen, wenn Ihre Lizenz entzogen wird.",
      "Alle der oben genannten sind wahr."], 0),
    ("15) Which of these statements about speed management is true?",
     "15) Welche dieser Aussagen über Geschwindigkeitsmanagement ist wahr?",
     ["When you double your speed, it will take four times the distance to stop.",
      "You should always drive at the posted speed limit.", "Speeding is not a major factor in crashes.",
      "All of the above are true."],
     ["Wenn Sie Ihre Geschwindigkeit verdoppeln, benötigen Sie die vierfache Strecke zum Anhalten.",
      "Sie sollten immer mit der angegebenen Höchstgeschwindigkeit fahren.",
      "Zu schnelles Fahren ist kein Hauptfaktor bei Unfällen.", "Alle der oben genannten sind wahr."], 0),
    ("16) What does 'Gross Combination Weight' (GCW) mean?", "16) Was bedeutet 'Gesamt-Zuggesamtgewicht' (GCW)?",
     ["The total weight of a powered unit plus all trailers.",
      "The weight of a powered unit plus the weight of its trailer.", "The total weight of all cargo in the truck.",
      "None of the above."], ["Das Gesamtgewicht einer angetriebenen Einheit plus aller Anhänger.",
                              "Das Gewicht einer angetriebenen Einheit plus das Gewicht ihres Anhängers.",
                              "Das Gesamtgewicht der gesamten Ladung im LKW.", "Keines der oben genannten."], 0),
    ("17) Which of these is true about shifting gears?",
     "17) Welche dieser Aussagen über das Schalten von Gängen ist wahr?",
     ["It is illegal to downshift when coming to a stop.", "You should look in your mirrors before shifting gears.",
      "You should always upshift immediately after starting on a hill.",
      "You should not try to shift gears while going through a curve."],
     ["Es ist illegal, beim Anhalten herunterzuschalten.",
      "Sie sollten in Ihre Spiegel schauen, bevor Sie Gänge schalten.",
      "Sie sollten immer sofort hochschalten, nachdem Sie an einem Hügel angefahren sind.",
      "Sie sollten nicht versuchen, Gänge zu schalten, während Sie eine Kurve durchfahren."], 3),
    ("18) What is the proper time to check your tire pressure?",
     "18) Was ist der richtige Zeitpunkt, um Ihren Reifendruck zu überprüfen?",
     ["When the vehicle is moving slowly.", "When the vehicle is parked on an incline.", "When the tires are hot.",
      "When the tires are cold."],
     ["Wenn das Fahrzeug sich langsam bewegt.", "Wenn das Fahrzeug an einer Steigung geparkt ist.",
      "Wenn die Reifen heiß sind.", "Wenn die Reifen kalt sind."], 3),
    ("19) Which of these is a good thing to do when steering to avoid a crash?",
     "19) Was ist eine gute Maßnahme beim Lenken, um einen Unfall zu vermeiden?",
     ["Don't apply the brake until after you have finished steering.", "Turn the wheel more than needed.",
      "Steer quickly and sharply to the side of the road.", "All of the above are true."],
     ["Betätigen Sie die Bremse erst, nachdem Sie mit dem Lenken fertig sind.",
      "Drehen Sie das Lenkrad mehr als nötig.", "Lenken Sie schnell und scharf zur Seite der Straße.",
      "Alle der oben genannten sind wahr."], 0),
    ("20) Which of these is true about the Commercial Driver's License (CDL)?",
     "20) Welche dieser Aussagen ist wahr über den Führerschein für Berufskraftfahrer (CDL)?",
     ["CDL holders are not allowed to use radar detectors in a commercial vehicle.",
      "CDL holders cannot drive a CMV if they have more than one license.", "All of the above are true."],
     ["CDL-Inhaber dürfen keine Radarwarner in einem Nutzfahrzeug verwenden.",
      "CDL-Inhaber dürfen kein Nutzfahrzeug fahren, wenn sie mehr als eine Lizenz besitzen.",
      "Alle der oben genannten sind wahr."], 2),
    ("21) How far ahead should you look while driving?", "21) Wie weit voraus sollten Sie beim Fahren schauen?",
     ["At least 12-15 seconds.", "About 1/4 mile.", "About 5-8 seconds.", "None of the above."],
     ["Mindestens 12-15 Sekunden.", "Etwa 1/4 Meile.", "Etwa 5-8 Sekunden.", "Keines der oben genannten."], 0),
    ("22) Which of these statements about alcohol is true?", "22) Welche dieser Aussagen über Alkohol ist wahr?",
     ["Alcohol first affects judgment and self-control.", "A driver can be unfit to drive after only one drink.",
      "You can be cited for DWI (Driving While Intoxicated) if your BAC is below .04%.", "All of the above are true."],
     ["Alkohol beeinträchtigt zuerst das Urteilsvermögen und die Selbstkontrolle.",
      "Ein Fahrer kann nach nur einem Getränk fahruntüchtig sein.",
      "Sie können wegen Trunkenheit am Steuer (DWI) angezeigt werden, wenn Ihr BAK unter 0,04% liegt.",
      "Alle der oben genannten sind wahr."], 0),
    ("23) A full stop is required at a railroad crossing when:",
     "23) Ein vollständiger Stopp ist an einem Bahnübergang erforderlich, wenn:",
     ["The nature of the cargo makes a stop mandatory under state or federal regulations.",
      "The vehicle is a school bus or passenger vehicle.", "Both A and B.", "None of the above."],
     ["Die Art der Ladung einen Stopp gemäß staatlicher oder bundesstaatlicher Vorschriften zwingend macht.",
      "Das Fahrzeug ein Schulbus oder ein Personenbeförderungsfahrzeug ist.", "Sowohl A als auch B.",
      "Keines der oben genannten."], 0),
    ("24) You should inspect the coupling of a semi-trailer and the fifth wheel when:",
     "24) Sie sollten die Kupplung eines Sattelaufliegers und die Sattelkupplung inspizieren, wenn:",
     ["You have completed the entire trip.", "The trailer is loaded with cargo.",
      "You are carrying a full passenger load.", "All of the above."],
     ["Sie die gesamte Fahrt abgeschlossen haben.", "Der Anhänger mit Ladung beladen ist.",
      "Sie eine volle Fahrgastladung befördern.", "Alle der oben genannten."], 1),
    ("25) Which of these is NOT a good thing to do when you have a tire fire?",
     "25) Was ist KEINE gute Maßnahme bei einem Reifenbrand?",
     ["Stop immediately in a safe area.", "Get out of the vehicle and move away from it.",
      "Use water to put out the fire.", "Use a fire extinguisher to put out the fire."],
     ["Sofort an einem sicheren Ort anhalten.", "Aus dem Fahrzeug aussteigen und sich davon entfernen.",
      "Wasser zum Löschen des Feuers verwenden.", "Einen Feuerlöscher zum Löschen des Feuers verwenden."], 2),
    ("26) You are driving a heavy vehicle. You must exit a highway using an off-ramp that curves downhill. You should:",
     "26) Sie fahren ein schweres Fahrzeug. Sie müssen eine Autobahn über eine bergab führende, kurvige Ausfahrt verlassen. Sie sollten:",
     ["Slow down to a safe speed before taking the curve.", "Brake hard as you enter the curve.",
      "Speed up slightly before the curve and coast through it.", "None of the above."],
     ["Vor der Kurve auf eine sichere Geschwindigkeit reduzieren.", "Beim Einfahren in die Kurve stark bremsen.",
      "Vor der Kurve leicht beschleunigen und durch sie hindurchrollen lassen.", "Keines der oben genannten."], 0),
    ("27) Which of these lights cannot be checked at the same time?",
     "27) Welche dieser Lichter können nicht gleichzeitig überprüft werden?",
     ["Headlights and clearance lights.", "Turn signals, brake lights, and 4-way flashers.",
      "High beams and low beams.", "All of the above can be checked at the same time."],
     ["Scheinwerfer und Begrenzungsleuchten.", "Blinker, Bremslichter und Warnblinkanlage.",
      "Fernlicht und Abblendlicht.", "Alle der oben genannten können gleichzeitig überprüft werden."], 1),
    ("28) The distance that you should look ahead of your vehicle while driving is about ___ at highway speed.",
     "28) Die Entfernung, die Sie beim Fahren auf der Autobahn voraus schauen sollten, beträgt etwa ___.",
     ["10-12 seconds", "1/4 mile", "100 feet", "200 feet"], ["10-12 Sekunden", "1/4 Meile", "100 Fuß", "200 Fuß"], 1),
    ("29) When hydraulic brakes fail, which of these should you do?",
     "29) Wenn hydraulische Bremsen ausfallen, was sollten Sie tun?",
     ["Use the air horn to warn others.", "Shift to a lower gear.", "Pump the brake pedal to bring the pressure up.",
      "Steer for the side of the road."],
     ["Die Lufthupe benutzen, um andere zu warnen.", "In einen niedrigeren Gang schalten.",
      "Das Bremspedal pumpen, um den Druck aufzubauen.", "Zur Seite der Straße lenken."], 2),
    ("30) In safe driving, what does 'communicating' mean?", "30) Was bedeutet 'Kommunizieren' beim sicheren Fahren?",
     ["Yelling at other drivers.", "Using your cell phone to call ahead.", "Letting others know what you intend to do.",
      "None of the above."],
     ["Andere Fahrer anschreien.", "Ihr Handy benutzen, um vorauszurufen.", "Andere wissen lassen, was Sie vorhaben.",
      "Keines der oben genannten."], 2),
    ("31) Which of these statements is true about warning other drivers of a hazard?",
     "31) Welche dieser Aussagen ist wahr über das Warnen anderer Fahrer vor einer Gefahr?",
     ["You should turn on your 4-way flashers or brake lights.", "You should tap your horn lightly.",
      "You should use your turn signal.", "All of the above are true."],
     ["Sie sollten Ihre Warnblinkanlage oder Bremslichter einschalten.", "Sie sollten leicht auf Ihre Hupe tippen.",
      "Sie sollten Ihren Blinker benutzen.", "Alle der oben genannten sind wahr."], 3),
    ("32) You are starting your vehicle in motion from a stop. As you release the brake pedal, you notice that your vehicle rolls backward. What should you do?",
     "32) Sie setzen Ihr Fahrzeug aus dem Stand in Bewegung. Als Sie das Bremspedal loslassen, bemerken Sie, dass Ihr Fahrzeug rückwärts rollt. Was sollten Sie tun?",
     ["Press the accelerator harder.", "Hold the brake pedal down.", "Apply the parking brake and use a low gear.",
      "None of the above."], ["Stärker auf das Gaspedal drücken.", "Das Bremspedal gedrückt halten.",
                              "Die Feststellbremse betätigen und einen niedrigen Gang verwenden.",
                              "Keines der oben genannten."], 2),
    ("33) The best drivers are those who:", "33) Die besten Fahrer sind diejenigen, die:",
     ["Keep their eyes on the road ahead.", "Watch only the front of the vehicle.", "Regularly check their mirrors.",
      "Never make any lane changes."],
     ["Ihre Augen auf die Straße vor sich gerichtet halten.", "Nur auf die Vorderseite des Fahrzeugs achten.",
      "Regelmäßig ihre Spiegel überprüfen.", "Niemals die Spur wechseln."], 2),
    ("34) Which of these is NOT a key item to check in a pre-trip inspection?",
     "34) Was ist KEIN wichtiger Punkt, der bei einer Inspektion vor der Fahrt überprüft werden muss?",
     ["The engine oil pressure.", "The water temperature gauge.", "The condition of the tires.",
      "The engine turbocharger."],
     ["Der Motoröldruck.", "Die Wassertemperaturanzeige.", "Der Zustand der Reifen.", "Der Motorturbolader."], 3),
    ("35) When performing a final inspection of your cargo and cargo tie-downs, you should pull over and check the cargo within:",
     "35) Bei der Endkontrolle Ihrer Ladung und Ladungssicherung sollten Sie anhalten und die Ladung innerhalb von ___ überprüfen:",
     ["50 miles of starting the trip.", "100 miles of starting the trip.", "The first hour of driving.",
      "None of the above."],
     ["50 Meilen nach Beginn der Fahrt.", "100 Meilen nach Beginn der Fahrt.", "Der ersten Stunde der Fahrt.",
      "Keines der oben genannten."], 0),
    ("36) What is the best way to see the sides and rear of your vehicle?",
     "36) Was ist der beste Weg, um die Seiten und das Heck Ihres Fahrzeugs zu sehen?",
     ["Check only your side mirrors.", "Check only your rearview mirror.", "Use your mirrors and turn your head.",
      "None of the above."], ["Nur Ihre Seitenspiegel überprüfen.", "Nur Ihren Rückspiegel überprüfen.",
                              "Ihre Spiegel benutzen und den Kopf drehen.", "Keines der oben genannten."], 2),
    ("37) You should put the gear selector in a low gear when traveling down a grade to:",
     "37) Sie sollten den Gangwählhebel in einen niedrigen Gang stellen, wenn Sie bergab fahren, um:",
     ["Save fuel.", "Avoid overheating the engine.", "Help slow the vehicle.", "None of the above."],
     ["Kraftstoff zu sparen.", "Eine Überhitzung des Motors zu vermeiden.", "Das Fahrzeug langsamer zu machen.",
      "Keines der oben genannten."], 2),
    ("38) Which of these statements about speed and stopping distance is true?",
     "38) Welche dieser Aussagen über Geschwindigkeit und Bremsweg ist wahr?",
     ["Speed does not affect total stopping distance.", "Wet roads can double your total stopping distance.",
      "You need less distance to stop when driving faster.", "All of the above are true."],
     ["Geschwindigkeit beeinflusst den gesamten Bremsweg nicht.",
      "Nasse Straßen können Ihren gesamten Bremsweg verdoppeln.",
      "Sie benötigen weniger Strecke zum Anhalten, wenn Sie schneller fahren.", "Alle der oben genannten sind wahr."],
     1),
    ("39) If you are being tailgated, you should:", "39) Wenn Sie bedrängt werden (Tailgating), sollten Sie:",
     ["Brake hard to warn the other driver.", "Speed up to gain distance.", "Increase your following distance.",
      "None of the above."],
     ["Stark bremsen, um den anderen Fahrer zu warnen.", "Beschleunigen, um Abstand zu gewinnen.",
      "Ihren Sicherheitsabstand vergrößern.", "Keines der oben genannten."], 2),
    ("40) Before you drive, you should check your oil level:",
     "40) Bevor Sie fahren, sollten Sie Ihren Ölstand überprüfen:",
     ["Daily.", "Weekly.", "Only when you hear a strange noise.", "None of the above."],
     ["Täglich.", "Wöchentlich.", "Nur wenn Sie ein seltsames Geräusch hören.", "Keines der oben genannten."], 0),
    ("41) Which of these is a sign of a tire blowout?", "41) Was ist ein Anzeichen für einen Reifenplatzer?",
     ["A slow hiss from the tire.", "A loud \"bang\".", "A sudden increase in vehicle speed.", "All of the above."],
     ["Ein langsames Zischen aus dem Reifen.", "Ein lauter \"Knall\".",
      "Eine plötzliche Zunahme der Fahrzeuggeschwindigkeit.", "Alle der oben genannten."], 1),
    ("42) If you have a heavy load that is high above the ground, you should:",
     "42) Wenn Sie eine schwere Ladung haben, die hoch über dem Boden liegt, sollten Sie:",
     ["Drive at the posted speed limit.", "Ignore windy conditions.", "Be careful when driving in windy conditions.",
      "None of the above."], ["Mit der angegebenen Höchstgeschwindigkeit fahren.", "Windige Bedingungen ignorieren.",
                              "Vorsichtig sein, wenn Sie bei windigen Bedingungen fahren.",
                              "Keines der oben genannten."], 2),
    ("43) A key thing to prevent a rollover is to:", "43) Ein wichtiges Mittel zur Verhinderung eines Überschlags ist:",
     ["Keep your speed down when taking curves.", "Load the cargo with a high center of gravity.",
      "Brake hard while turning.", "All of the above."],
     ["Ihre Geschwindigkeit beim Durchfahren von Kurven niedrig halten.",
      "Die Ladung mit einem hohen Schwerpunkt laden.", "Beim Abbiegen stark bremsen.", "Alle der oben genannten."], 0),
    ("44) Which of these statements is true about backing a heavy vehicle?",
     "44) Welche dieser Aussagen ist wahr über das Rückwärtsfahren mit einem schweren Fahrzeug?",
     ["It is safest to back up quickly.", "You should always rely on your mirrors only.",
      "You should avoid backing whenever possible.", "All of the above are true."],
     ["Es ist am sichersten, schnell rückwärts zu fahren.", "Sie sollten sich immer nur auf Ihre Spiegel verlassen.",
      "Sie sollten das Rückwärtsfahren wann immer möglich vermeiden.", "Alle der oben genannten sind wahr."], 2),
    ("45) If you are being forced off the road, you should:",
     "45) Wenn Sie gezwungen werden, die Straße zu verlassen, sollten Sie:",
     ["Brake hard and stay in your lane.", "Steer into the side of the road if necessary.",
      "Signal to the other driver to slow down.", "All of the above are true."],
     ["Stark bremsen und in Ihrer Spur bleiben.", "Bei Bedarf auf die Seite der Straße lenken.",
      "Dem anderen Fahrer signalisieren, langsamer zu werden.", "Alle der oben genannten sind wahr."], 1),
    ("46) What is the key to successfully navigating a curve?",
     "46) Was ist der Schlüssel, um eine Kurve erfolgreich zu durchfahren?",
     ["Accelerate as you enter the curve.", "Maintain a high speed through the curve.",
      "Slow down before entering the curve.", "None of the above."],
     ["Beschleunigen Sie, wenn Sie in die Kurve einfahren.",
      "Halten Sie eine hohe Geschwindigkeit durch die Kurve bei.",
      "Reduzieren Sie die Geschwindigkeit, bevor Sie in die Kurve einfahren.", "Keines der oben genannten."], 2),
    ("47) Which of these is a sign of tire failure?", "47) Was ist ein Anzeichen für einen Reifenschaden?",
     ["A loud noise (e.g. bang).", "Vibration or a thump.", "All of the above.", "None of the above."],
     ["Ein lautes Geräusch (z.B. Knall).", "Vibration oder ein Poltern.", "Alle der oben genannten.",
      "Keines der oben genannten."], 2),
    ("48) Which of these should you do during your trip?", "48) Was sollten Sie während Ihrer Fahrt tun?",
     ["Check your tires every time you stop.", "Drive faster than the posted limit to make up time.",
      "Never stop for more than a quick break.", "None of the above."],
     ["Ihre Reifen jedes Mal überprüfen, wenn Sie anhalten.",
      "Schneller als die angegebene Höchstgeschwindigkeit fahren, um Zeit aufzuholen.",
      "Nie länger als für eine kurze Pause anhalten.", "Keines der oben genannten."], 0),
    ("49) Which of these is a good rule for using your horn?",
     "49) Was ist eine gute Regel für die Verwendung Ihrer Hupe?", ["Use the horn frequently to signal your presence.",
                                                                    "Hold the horn down for several seconds if you need to warn someone.",
                                                                    "Tap the horn lightly when you need to use it.",
                                                                    "None of the above."],
     ["Die Hupe häufig benutzen, um Ihre Anwesenheit zu signalisieren.",
      "Die Hupe für mehrere Sekunden gedrückt halten, wenn Sie jemanden warnen müssen.",
      "Leicht auf die Hupe tippen, wenn Sie sie benutzen müssen.", "Keines der oben genannten."], 2),
    ("50) How can you tell if the engine is having problems?",
     "50) Wie können Sie feststellen, ob der Motor Probleme hat?",
     ["By checking the oil pressure gauge.", "By checking the temperature gauge.", "All of the above.",
      "None of the above."],
     ["Durch Überprüfen der Öldruckanzeige.", "Durch Überprüfen der Temperaturanzeige.", "Alle der oben genannten.",
      "Keines der oben genannten."], 2),
    ("51) Which of these statements about overhead clearance is true?",
     "51) Welche dieser Aussagen über die Durchfahrtshöhe ist wahr?",
     ["The maximum legal height of a vehicle is the same in all states.",
      "Allow a few inches of clearance over the total vehicle height.",
      "The actual height of your vehicle will not change.", "All of the above are true."],
     ["Die maximal zulässige Höhe eines Fahrzeugs ist in allen Staaten gleich.",
      "Lassen Sie einige Zentimeter Spielraum über die Gesamthöhe des Fahrzeugs hinaus.",
      "Die tatsächliche Höhe Ihres Fahrzeugs wird sich nicht ändern.", "Alle der oben genannten sind wahr."], 2),
    ("52) Which of these is NOT a key item to check on the bus during the trip?",
     "52) Was ist KEIN wichtiger Punkt, der während der Fahrt im Bus überprüft werden muss?",
     ["Your instruments.", "Your cargo and cargo tie-downs.", "Your tire pressure.", "All of the above."],
     ["Ihre Instrumente.", "Ihre Ladung und Ladungssicherung.", "Ihr Reifendruck.", "Alle der oben genannten."], 1),
    ("53) Which of these statements about vehicle inspection is true?",
     "53) Welche dieser Aussagen über die Fahrzeuginspektion ist wahr?",
     ["If you have a problem, you should report it to your supervisor immediately.",
      "It is better to fix a major problem on the road.", "All of the above are true.", "None of the above."],
     ["Wenn Sie ein Problem haben, sollten Sie es sofort Ihrem Vorgesetzten melden.",
      "Es ist besser, ein größeres Problem unterwegs zu beheben.", "Alle der oben genannten sind wahr.",
      "Keines der oben genannten."], 1),
    ("54) When driving in reverse, you should:", "54) Beim Rückwärtsfahren sollten Sie:",
     ["Only use your mirrors.", "Back up as fast as possible.", "Avoid backing whenever possible.",
      "All of the above."], ["Nur Ihre Spiegel benutzen.", "So schnell wie möglich rückwärts fahren.",
                             "Rückwärtsfahren wann immer möglich vermeiden.", "Alle der oben genannten."], 2),
    ("55) Which of these is a common cause of serious accidents?",
     "55) Was ist eine häufige Ursache für schwere Unfälle?",
     ["Driving too fast for the conditions.", "Overloading the vehicle.", "All of the above.", "None of the above."],
     ["Zu schnelles Fahren für die Bedingungen.", "Überladen des Fahrzeugs.", "Alle der oben genannten.",
      "Keines der oben genannten."], 2),
    ("56) What is the term for when the rear wheels lose traction and the vehicle skids sideways?",
     "56) Was ist der Begriff dafür, wenn die Hinterräder die Traktion verlieren und das Fahrzeug seitlich rutscht?",
     ["Hydroplaning.", "Over-steer.", "Skidding.", "None of the above."],
     ["Aquaplaning.", "Übersteuern.", "Schleudern.", "Keines der oben genannten."], 2),
    ("57) How long does it take for a normal driver to react to a problem on the road?",
     "57) Wie lange dauert es, bis ein normaler Fahrer auf ein Problem auf der Straße reagiert?",
     ["1/2 second.", "1 second.", "3/4 second.", "1 1/2 seconds."],
     ["1/2 Sekunde.", "1 Sekunde.", "3/4 Sekunde.", "1 1/2 Sekunden."], 2),
    ("58) Which of these is a good practice when driving at night?",
     "58) Was ist eine gute Praxis beim Fahren in der Nacht?",
     ["Keep your speed high.", "Dim your headlights to low beam when following another vehicle.",
      "Never use your high beams.", "All of the above."], ["Halten Sie Ihre Geschwindigkeit hoch.",
                                                           "Dimmen Sie Ihre Scheinwerfer auf Abblendlicht, wenn Sie einem anderen Fahrzeug folgen.",
                                                           "Benutzen Sie niemals Ihr Fernlicht.",
                                                           "Alle der oben genannten."], 1),
    ("59) Which of these is true about shifting gears?",
     "59) Welche dieser Aussagen ist wahr über das Schalten von Gängen?",
     ["You should always use the clutch when downshifting.", "Downshifting is a good way to control your speed.",
      "All of the above are true.", "None of the above."],
     ["Sie sollten beim Herunterschalten immer die Kupplung benutzen.",
      "Herunterschalten ist eine gute Möglichkeit, Ihre Geschwindigkeit zu kontrollieren.",
      "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 1),
    ("60) Which of these is a proper use of the braking system?",
     "60) Was ist eine ordnungsgemäße Verwendung des Bremssystems?",
     ["Use light steady pressure when going downhill.", "Use stab braking in an emergency.",
      "Avoid pumping the brakes.", "All of the above."],
     ["Leichten, gleichmäßigen Druck beim Bergabfahren verwenden.", "Stoßbremsung im Notfall verwenden.",
      "Pumpen der Bremsen vermeiden.", "Alle der oben genannten."], 3),
    ("61) Which of these is a good reason to use a low gear?",
     "61) Was ist ein guter Grund, einen niedrigen Gang zu verwenden?",
     ["To save fuel.", "To control your speed on a downgrade.", "To avoid engine overheating.", "All of the above."],
     ["Um Kraftstoff zu sparen.", "Um Ihre Geschwindigkeit an einem Gefälle zu kontrollieren.",
      "Um eine Motorüberhitzung zu vermeiden.", "Alle der oben genannten."], 1),
    ("62) Which of these is true about a vehicle inspection report?",
     "62) Welche dieser Aussagen ist wahr über einen Fahrzeuginspektionsbericht?",
     ["It must be filled out before and after the trip.", "It must be kept for 30 days.", "All of the above are true.",
      "None of the above."],
     ["Er muss vor und nach der Fahrt ausgefüllt werden.", "Er muss 30 Tage lang aufbewahrt werden.",
      "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 2),
    ("63) Which of these is a true statement about vehicle weight?",
     "63) Welche dieser Aussagen ist wahr über das Fahrzeuggewicht?",
     ["The maximum legal weight is the same for all states.",
      "You should check your vehicle weight before starting a trip.", "All of the above are true.",
      "None of the above."], ["Das maximal zulässige Gewicht ist in allen Staaten gleich.",
                              "Sie sollten Ihr Fahrzeuggewicht vor Fahrtbeginn überprüfen.",
                              "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 1),
    ("64) When driving, you should monitor your gauges:", "64) Beim Fahren sollten Sie Ihre Anzeigen überwachen:",
     ["Hourly.", "Continuously.", "Only when the warning lights come on.", "None of the above."],
     ["Stündlich.", "Kontinuierlich.", "Nur wenn die Warnleuchten angehen.", "Keines der oben genannten."], 1),
    ("65) Which of these is a sign of a vehicle malfunction?", "65) Was ist ein Anzeichen für eine Fahrzeugstörung?",
     ["A sudden noise.", "A strange smell.", "A warning light on the dash.", "All of the above."],
     ["Ein plötzliches Geräusch.", "Ein seltsamer Geruch.", "Eine Warnleuchte auf dem Armaturenbrett.",
      "Alle der oben genannten."], 3),
    ("66) Which of these is a common problem with large vehicles on curves?",
     "66) Was ist ein häufiges Problem bei großen Fahrzeugen in Kurven?",
     ["They are more likely to under-steer.", "They are more likely to roll over.", "They are more likely to skid.",
      "None of the above."],
     ["Sie neigen eher zum Untersteuern.", "Sie neigen eher zum Überschlagen.", "Sie neigen eher zum Schleudern.",
      "Keines der oben genannten."], 1),
    ("67) You are checking your suspension system for a pre-trip inspection. Which of these is true?",
     "67) Sie überprüfen Ihr Aufhängungssystem für eine Inspektion vor der Fahrt. Welche dieser Aussagen ist wahr?",
     ["A broken leaf spring can be ignored.", "Shock absorbers should be checked for leaks.",
      "All of the above are true.", "None of the above."],
     ["Eine gebrochene Blattfeder kann ignoriert werden.", "Stoßdämpfer sollten auf Undichtigkeiten überprüft werden.",
      "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 1),
    ("68) Which of these is a good practice when dealing with aggressive drivers?",
     "68) Was ist eine gute Praxis im Umgang mit aggressiven Fahrern?",
     ["Respond in kind.", "Avoid eye contact.", "Drive faster to get away.", "All of the above."],
     ["Gleiches mit Gleichem vergelten.", "Augenkontakt vermeiden.", "Schneller fahren, um wegzukommen.",
      "Alle der oben genannten."], 1),
    ("69) Which of these is a good thing to do when you encounter a distracted driver?",
     "69) Was ist eine gute Maßnahme, wenn Sie einem abgelenkten Fahrer begegnen?",
     ["Signal your frustration.", "Maintain a safe following distance.", "Drive aggressively to pass quickly.",
      "All of the above."], ["Ihre Frustration signalisieren.", "Einen sicheren Sicherheitsabstand einhalten.",
                             "Aggressiv fahren, um schnell zu überholen.", "Alle der oben genannten."], 1),
    ("70) Which of these is true about the use of hazard warning lights?",
     "70) Welche dieser Aussagen ist wahr über die Verwendung von Warnblinkleuchten?",
     ["They should only be used when the vehicle is completely stopped.",
      "They should be used to warn others of a problem.", "All of the above are true.", "None of the above."],
     ["Sie sollten nur verwendet werden, wenn das Fahrzeug vollständig steht.",
      "Sie sollten verwendet werden, um andere vor einem Problem zu warnen.", "Alle der oben genannten sind wahr.",
      "Keines der oben genannten."], 1),
    ("71) Which of these is a factor that determines your vehicle's stopping distance?",
     "71) Was ist ein Faktor, der den Bremsweg Ihres Fahrzeugs bestimmt?",
     ["Reaction time.", "Brake lag.", "Weight and speed.", "All of the above."],
     ["Reaktionszeit.", "Bremsverzögerung.", "Gewicht und Geschwindigkeit.", "Alle der oben genannten."], 3),
    ("72) What is the most important thing to remember about braking in a curve?",
     "72) Was ist das Wichtigste, woran man beim Bremsen in einer Kurve denken sollte?",
     ["Brake lightly before entering the curve.", "Brake hard while in the curve.",
      "Brake only after exiting the curve.", "None of the above."],
     ["Leicht bremsen, bevor Sie in die Kurve einfahren.", "Stark bremsen, während Sie sich in der Kurve befinden.",
      "Erst nach dem Verlassen der Kurve bremsen.", "Keines der oben genannten."], 0),
    ("73) Which of these is true about distracted driving?",
     "73) Welche dieser Aussagen ist wahr über abgelenktes Fahren?",
     ["Talking on a cell phone is generally safe for CDL drivers.", "Eating while driving is not a distraction.",
      "Distracted driving is a major cause of crashes.", "All of the above are true."],
     ["Das Telefonieren mit einem Mobiltelefon ist für CDL-Fahrer im Allgemeinen sicher.",
      "Essen während der Fahrt ist keine Ablenkung.", "Ablenkendes Fahren ist eine Hauptursache für Unfälle.",
      "Alle der oben genannten sind wahr."], 2),
    ("74) Which of these is true about a CDL holder who is stopped for an alcohol violation?",
     "74) Welche dieser Aussagen ist wahr über einen CDL-Inhaber, der wegen eines Alkohol-Verstoßes angehalten wird?",
     ["They must be immediately taken out of service for 24 hours.",
      "They will lose their CDL for one year if the BAC is 0.04% or higher.", "All of the above are true.",
      "None of the above."], ["Sie müssen sofort für 24 Stunden außer Dienst gestellt werden.",
                              "Sie verlieren ihren CDL für ein Jahr, wenn der BAK 0,04% oder höher ist.",
                              "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 2),
    ("75) Which of these is true about the space you need when driving a large vehicle?",
     "75) Welche dieser Aussagen ist wahr über den Platz, den Sie beim Fahren eines großen Fahrzeugs benötigen?",
     ["You need more space to stop than a car.", "You need more space to turn than a car.",
      "All of the above are true.", "None of the above."],
     ["Sie benötigen mehr Platz zum Anhalten als ein PKW.", "Sie benötigen mehr Platz zum Abbiegen als ein PKW.",
      "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 2),
    ("76) Which of these should you do to prevent fatigue?", "76) Was sollten Sie tun, um Müdigkeit vorzubeugen?",
     ["Take short naps.", "Drink a lot of coffee.", "Pull over and rest when tired.", "All of the above."],
     ["Kurze Nickerchen machen.", "Viel Kaffee trinken.", "Anhalten und sich ausruhen, wenn Sie müde sind.",
      "Alle der oben genannten."], 2),
    ("77) Which of these is a potential sign of a brake problem?",
     "77) Was ist ein potenzielles Anzeichen für ein Bremsproblem?",
     ["The brakes feel spongy.", "The vehicle pulls to one side when braking.", "All of the above.",
      "None of the above."],
     ["Die Bremsen fühlen sich schwammig an.", "Das Fahrzeug zieht beim Bremsen zu einer Seite.",
      "Alle der oben genannten.", "Keines der oben genannten."], 2),
    ("78) Which of these is true about checking your vehicle's lights?",
     "78) Welche dieser Aussagen ist wahr über das Überprüfen der Lichter Ihres Fahrzeugs?",
     ["All lights must be clean and working.", "You should check them before every trip.", "All of the above are true.",
      "None of the above."],
     ["Alle Lichter müssen sauber und funktionstüchtig sein.", "Sie sollten sie vor jeder Fahrt überprüfen.",
      "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 2),
    ("79) What is the best way to handle a curve if you realize you are going too fast?",
     "79) Was ist der beste Weg, eine Kurve zu bewältigen, wenn Sie feststellen, dass Sie zu schnell sind?",
     ["Brake hard and steer sharply.", "Ease off the accelerator and steer gently.",
      "Accelerate to stabilize the vehicle.", "None of the above."],
     ["Stark bremsen und scharf lenken.", "Vom Gas gehen und sanft lenken.",
      "Beschleunigen, um das Fahrzeug zu stabilisieren.", "Keines der oben genannten."], 1),
    ("80) Which of these is true about a vehicle's center of gravity?",
     "80) Welche dieser Aussagen ist wahr über den Schwerpunkt eines Fahrzeugs?",
     ["A low center of gravity is safer.", "A high center of gravity increases the risk of rollover.",
      "All of the above are true.", "None of the above."],
     ["Ein niedriger Schwerpunkt ist sicherer.", "Ein hoher Schwerpunkt erhöht das Risiko eines Überschlags.",
      "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 2),
    ("81) Which of these is a key factor in vehicle control on hills?",
     "81) Was ist ein Schlüsselfaktor für die Fahrzeugkontrolle an Steigungen?",
     ["Proper gear selection.", "Ignoring the vehicle weight.", "Maintaining high speed.", "None of the above."],
     ["Korrekte Gangwahl.", "Ignorieren des Fahrzeuggewichts.", "Beibehaltung einer hohen Geschwindigkeit.",
      "Keines der oben genannten."], 0),
    ("82) Which of these is true about vehicle suspension?",
     "82) Welche dieser Aussagen ist wahr über die Fahrzeugaufhängung?",
     ["It provides a smooth ride.", "It keeps the axles in place.", "All of the above are true.", "None of the above."],
     ["Sie sorgt für eine ruhige Fahrt.", "Sie hält die Achsen an Ort und Stelle.",
      "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 2),
    ("83) Which of these is true about hazardous materials?", "83) Welche dieser Aussagen ist wahr über Gefahrgüter?",
     ["You must know the proper placarding requirements.", "You must know how to properly handle the materials.",
      "All of the above are true.", "None of the above."],
     ["Sie müssen die korrekten Kennzeichnungsanforderungen kennen.",
      "Sie müssen wissen, wie man die Materialien richtig handhabt.", "Alle der oben genannten sind wahr.",
      "Keines der oben genannten."], 2),
    ("84) Which of these is true about engine compartment inspection?",
     "84) Welche dieser Aussagen ist wahr über die Inspektion des Motorraums?",
     ["You should check for oil leaks.", "You should check the fluid levels.", "All of the above are true.",
      "None of the above."], ["Sie sollten auf Öllecks prüfen.", "Sie sollten die Flüssigkeitsstände überprüfen.",
                              "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 2),
    ("85) Which of these is true about vehicle documents?",
     "85) Welche dieser Aussagen ist wahr über Fahrzeugdokumente?",
     ["You must carry your CDL at all times.", "You must have vehicle registration.", "All of the above are true.",
      "None of the above."],
     ["Sie müssen Ihren CDL jederzeit mit sich führen.", "Sie müssen eine Fahrzeugregistrierung haben.",
      "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 2),
    ("86) Which of these is true about securing cargo?",
     "86) Welche dieser Aussagen ist wahr über die Sicherung der Ladung?",
     ["Cargo must be covered.", "Cargo must be stable.", "All of the above are true.", "None of the above."],
     ["Ladung muss abgedeckt sein.", "Ladung muss stabil sein.", "Alle der oben genannten sind wahr.",
      "Keines der oben genannten."], 2),
    ("87) Which of these is true about tires?", "87) Welche dieser Aussagen ist wahr über Reifen?",
     ["Tires should be replaced if they show excessive wear.", "Tires of different sizes can be used on the same axle.",
      "All of the above are true.", "None of the above."],
     ["Reifen sollten ersetzt werden, wenn sie übermäßigen Verschleiß aufweisen.",
      "Reifen unterschiedlicher Größe können an derselben Achse verwendet werden.",
      "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 0),
    ("88) Which of these is true about checking wheel bearings?",
     "88) Welche dieser Aussagen ist wahr über das Überprüfen von Radlagern?",
     ["They should not have excessive play.", "They should be checked for leaks.", "All of the above are true.",
      "None of the above."],
     ["Sie sollten kein übermäßiges Spiel haben.", "Sie sollten auf Undichtigkeiten überprüft werden.",
      "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 2),
    ("89) Which of these is true about the clutch and shifting?",
     "89) Welche dieser Aussagen ist wahr über die Kupplung und das Schalten?",
     ["The clutch should be pressed all the way down when shifting.",
      "You should 'fan' the clutch to speed up shifting.", "All of the above are true.", "None of the above."],
     ["Die Kupplung sollte beim Schalten ganz durchgedrückt werden.",
      "Sie sollten die Kupplung 'fächern', um das Schalten zu beschleunigen.", "Alle der oben genannten sind wahr.",
      "Keines der oben genannten."], 0),
    ("90) Which of these is true about downshifting before a curve?",
     "90) Welche dieser Aussagen ist wahr über das Herunterschalten vor einer Kurve?",
     ["It helps you control your speed.", "It should be done while you are in the curve.", "All of the above are true.",
      "None of the above."], ["Es hilft Ihnen, Ihre Geschwindigkeit zu kontrollieren.",
                              "Es sollte getan werden, während Sie sich in der Kurve befinden.",
                              "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 0),
    ("91) Which of these is true about the use of speedometers?",
     "91) Welche dieser Aussagen ist wahr über die Verwendung von Tachometern?",
     ["They must be accurate.", "They are only required for vehicles over a certain weight.",
      "All of the above are true.", "None of the above."],
     ["Sie müssen genau sein.", "Sie sind nur für Fahrzeuge über einem bestimmten Gewicht erforderlich.",
      "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 0),
    ("92) Which of these is true about the use of brake lights?",
     "92) Welche dieser Aussagen ist wahr über die Verwendung von Bremslichtern?",
     ["They are required to be operational.", "They should be checked before every trip.", "All of the above are true.",
      "None of the above."], ["Sie müssen funktionsfähig sein.", "Sie sollten vor jeder Fahrt überprüft werden.",
                              "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 2),
    ("93) Which of these is true about the steering system?",
     "93) Welche dieser Aussagen ist wahr über das Lenksystem?",
     ["The steering wheel should have no more than 10 degrees of play.",
      "The power steering belt should be checked for tightness.", "All of the above are true.", "None of the above."],
     ["Das Lenkrad sollte nicht mehr als 10 Grad Spiel haben.",
      "Der Servolenkriemen sollte auf Festigkeit überprüft werden.", "Alle der oben genannten sind wahr.",
      "Keines der oben genannten."], 2),
    ("94) Which of these is true about the cooling system?", "94) Welche dieser Aussagen ist wahr über das Kühlsystem?",
     ["The coolant level should be checked.", "The radiator cap should be removed when the engine is hot.",
      "All of the above are true.", "None of the above."], ["Der Kühlmittelstand sollte überprüft werden.",
                                                            "Der Kühlerverschluss sollte entfernt werden, wenn der Motor heiß ist.",
                                                            "Alle der oben genannten sind wahr.",
                                                            "Keines der oben genannten."], 0),
    ("95) Which of these is true about the oil pressure gauge?",
     "95) Welche dieser Aussagen ist wahr über die Öldruckanzeige?",
     ["A low reading can indicate a problem.", "The gauge should be checked continuously.",
      "All of the above are true.", "None of the above."],
     ["Ein niedriger Messwert kann auf ein Problem hinweisen.", "Die Anzeige sollte kontinuierlich überprüft werden.",
      "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 2),
    ("96) Which of these is true about vehicle speed?",
     "96) Welche dieser Aussagen ist wahr über die Fahrzeuggeschwindigkeit?",
     ["High speed reduces your ability to stop safely.", "High speed improves your fuel efficiency.",
      "All of the above are true.", "None of the above."],
     ["Hohe Geschwindigkeit reduziert Ihre Fähigkeit, sicher anzuhalten.",
      "Hohe Geschwindigkeit verbessert Ihre Kraftstoffeffizienz.", "Alle der oben genannten sind wahr.",
      "Keines der oben genannten."], 0),
    ("97) Which of these is true about the use of turn signals?",
     "97) Welche dieser Aussagen ist wahr über die Verwendung von Blinkern?",
     ["They should be used to communicate your intentions.", "They are only required when changing lanes.",
      "All of the above are true.", "None of the above."],
     ["Sie sollten verwendet werden, um Ihre Absichten zu kommunizieren.",
      "Sie sind nur beim Spurwechsel erforderlich.", "Alle der oben genannten sind wahr.",
      "Keines der oben genannten."], 0),
    ("98) Which of these is true about following distance?",
     "98) Welche dieser Aussagen ist wahr über den Sicherheitsabstand?",
     ["You should use the four-second rule for heavy vehicles.",
      "The following distance should be increased in bad weather.", "All of the above are true.", "None of the above."],
     ["Sie sollten die Vier-Sekunden-Regel für schwere Fahrzeuge verwenden.",
      "Der Sicherheitsabstand sollte bei schlechtem Wetter vergrößert werden.", "Alle der oben genannten sind wahr.",
      "Keines der oben genannten."], 2),
    ("99) Which of these is true about driving in traffic?",
     "99) Welche dieser Aussagen ist wahr über das Fahren im Verkehr?",
     ["You should constantly search for hazards.", "You should focus only on the vehicle in front of you.",
      "All of the above are true.", "None of the above."],
     ["Sie sollten ständig nach Gefahren suchen.", "Sie sollten sich nur auf das Fahrzeug vor Ihnen konzentrieren.",
      "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 0),
    ("100) Which of these is true about the engine stop controls?",
     "100) Welche dieser Aussagen ist wahr über die Motorstopp-Steuerungen?",
     ["They should be checked for proper function.", "They are not required for diesel engines.",
      "All of the above are true.", "None of the above."],
     ["Sie sollten auf ordnungsgemäße Funktion überprüft werden.", "Sie sind für Dieselmotoren nicht erforderlich.",
      "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 0),
    ("101) Which of these is true about the emergency brake system?",
     "101) Welche dieser Aussagen ist wahr über das Notbremssystem?",
     ["It uses parts of the service and parking brake systems.", "It is only used when the service brakes fail.",
      "All of the above are true.", "None of the above."],
     ["Es verwendet Teile des Betriebs- und Feststellbremssystems.",
      "Es wird nur verwendet, wenn die Betriebsbremsen ausfallen.", "Alle der oben genannten sind wahr.",
      "Keines der oben genannten."], 2),
    ("102) Which of these is true about the use of the clutch?",
     "102) Welche dieser Aussagen ist wahr über die Verwendung der Kupplung?",
     ["The clutch should be released slowly.", "The clutch should be released quickly.", "All of the above are true.",
      "None of the above."],
     ["Die Kupplung sollte langsam gelöst werden.", "Die Kupplung sollte schnell gelöst werden.",
      "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 0),
    ("103) Which of these is true about the vehicle battery?",
     "103) Welche dieser Aussagen ist wahr über die Fahrzeugbatterie?",
     ["The battery terminals should be clean.", "The battery fluid level should be checked.",
      "All of the above are true.", "None of the above."],
     ["Die Batteriepole sollten sauber sein.", "Der Batteriestand sollte überprüft werden.",
      "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 2),
    ("104) Which of these is true about the drive shaft?",
     "104) Welche dieser Aussagen ist wahr über die Antriebswelle?",
     ["It should be checked for twisting or bending.", "It connects the transmission to the differential.",
      "All of the above are true.", "None of the above."],
     ["Sie sollte auf Verdrehung oder Biegung überprüft werden.", "Sie verbindet das Getriebe mit dem Differential.",
      "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 2),
    ("105) Which of these is true about the suspension system?",
     "105) Welche dieser Aussagen ist wahr über das Aufhängungssystem?",
     ["It keeps the tires in contact with the road.", "It supports the vehicle weight.", "All of the above are true.",
      "None of the above."], ["Es hält die Reifen in Kontakt mit der Straße.", "Es trägt das Fahrzeuggewicht.",
                              "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 2),
    ("106) Which of these is true about the brake drum or rotor?",
     "106) Welche dieser Aussagen ist wahr über die Bremstrommel oder den Rotor?",
     ["It should be free of cracks.", "It should be checked for excessive wear.", "All of the above are true.",
      "None of the above."],
     ["Er sollte frei von Rissen sein.", "Er sollte auf übermäßigen Verschleiß überprüft werden.",
      "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 2),
    ("107) Which of these is true about the brake lines and hoses?",
     "107) Welche dieser Aussagen ist wahr über die Bremsleitungen und -schläuche?",
     ["They should be free of leaks.", "They should not be cracked or frayed.", "All of the above are true.",
      "None of the above."],
     ["Sie sollten frei von Undichtigkeiten sein.", "Sie sollten nicht gerissen oder ausgefranst sein.",
      "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 2),
    ("108) Which of these is true about the slack adjusters?",
     "108) Welche dieser Aussagen ist wahr über die Gestängesteller?",
     ["They should be checked for proper adjustment.", "They must be manually adjusted on all vehicles.",
      "All of the above are true.", "None of the above."], ["Sie sollten auf korrekte Einstellung überprüft werden.",
                                                            "Sie müssen an allen Fahrzeugen manuell eingestellt werden.",
                                                            "Alle der oben genannten sind wahr.",
                                                            "Keines der oben genannten."], 0),
    ("109) Which of these is true about the use of the steering wheel?",
     "109) Welche dieser Aussagen ist wahr über die Verwendung des Lenkrads?",
     ["You should keep both hands on the wheel.", "You should use a 'push-pull' method.", "All of the above are true.",
      "None of the above."],
     ["Sie sollten beide Hände am Lenkrad halten.", "Sie sollten die 'Push-Pull'-Methode verwenden.",
      "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 2),
    ("110) Which of these is true about the engine compartment?",
     "110) Welche dieser Aussagen ist wahr über den Motorraum?",
     ["It should be free of excessive oil or grease.", "The belts and hoses should be checked.",
      "All of the above are true.", "None of the above."],
     ["Er sollte frei von übermäßigem Öl oder Fett sein.", "Die Riemen und Schläuche sollten überprüft werden.",
      "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 2),
    ("111) Which of these is true about the mirrors?", "111) Welche dieser Aussagen ist wahr über die Spiegel?",
     ["They should be clean and properly adjusted.", "They should be checked frequently while driving.",
      "All of the above are true.", "None of the above."],
     ["Sie sollten sauber und richtig eingestellt sein.", "Sie sollten während der Fahrt häufig überprüft werden.",
      "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 2),
    ("112) Which of these is true about the wipers and washers?",
     "112) Welche dieser Aussagen ist wahr über die Scheibenwischer und -waschanlage?",
     ["They must be working properly.", "They should be checked before every trip.", "All of the above are true.",
      "None of the above."],
     ["Sie müssen ordnungsgemäß funktionieren.", "Sie sollten vor jeder Fahrt überprüft werden.",
      "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 2),
    ("113) Which of these is true about the safety equipment?",
     "113) Welche dieser Aussagen ist wahr über die Sicherheitsausrüstung?",
     ["You must have a fire extinguisher.", "You must have spare fuses (unless equipped with circuit breakers).",
      "All of the above are true.", "None of the above."], ["Sie müssen einen Feuerlöscher haben.",
                                                            "Sie müssen Ersatzsicherungen haben (es sei denn, das Fahrzeug ist mit Schutzschaltern ausgestattet).",
                                                            "Alle der oben genannten sind wahr.",
                                                            "Keines der oben genannten."], 2),
    ("114) Which of these is true about the use of the brakes on a downgrade?",
     "114) Welche dieser Aussagen ist wahr über die Verwendung der Bremsen an einem Gefälle?",
     ["You should use the engine brake.", "You should use the service brakes only as a supplement.",
      "All of the above are true.", "None of the above."],
     ["Sie sollten die Motorbremse verwenden.", "Sie sollten die Betriebsbremsen nur als Ergänzung verwenden.",
      "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 2),
    ("115) Which of these is true about shifting down a grade?",
     "115) Welche dieser Aussagen ist wahr über das Herunterschalten an einem Gefälle?",
     ["Downshift before starting down the grade.", "Downshift while going down the grade.",
      "All of the above are true.", "None of the above."],
     ["Vor dem Beginn des Gefälles herunterschalten.", "Während der Fahrt bergab herunterschalten.",
      "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 0),
    ("116) Which of these is true about the effects of weather on stopping distance?",
     "116) Welche dieser Aussagen ist wahr über die Auswirkungen des Wetters auf den Bremsweg?",
     ["Wet roads increase stopping distance.", "Icy roads significantly increase stopping distance.",
      "All of the above are true.", "None of the above."],
     ["Nasse Straßen erhöhen den Bremsweg.", "Vereiste Straßen erhöhen den Bremsweg erheblich.",
      "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 2),
    ("117) Which of these is true about the use of the service brakes?",
     "117) Welche dieser Aussagen ist wahr über die Verwendung der Betriebsbremsen?",
     ["They should be used to slow the vehicle gradually.",
      "They should be used to maintain a slow speed on a downgrade.", "All of the above are true.",
      "None of the above."], ["Sie sollten verwendet werden, um das Fahrzeug allmählich zu verlangsamen.",
                              "Sie sollten verwendet werden, um eine langsame Geschwindigkeit an einem Gefälle beizubehalten.",
                              "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 2),
    ("118) Which of these is true about the air brake system?",
     "118) Welche dieser Aussagen ist wahr über das Luftbremssystem?",
     ["It must be working properly before driving.", "The low air pressure warning must be functional.",
      "All of the above are true.", "None of the above."], ["Es muss vor der Fahrt ordnungsgemäß funktionieren.",
                                                            "Die Warnung bei niedrigem Luftdruck muss funktionsfähig sein.",
                                                            "Alle der oben genannten sind wahr.",
                                                            "Keines der oben genannten."], 2),
    ("119) Which of these is true about the use of the parking brake?",
     "119) Welche dieser Aussagen ist wahr über die Verwendung der Feststellbremse?",
     ["It should be set whenever you leave the vehicle.", "It should be checked during the pre-trip inspection.",
      "All of the above are true.", "None of the above."],
     ["Sie sollte immer dann angezogen werden, wenn Sie das Fahrzeug verlassen.",
      "Sie sollte während der Inspektion vor der Fahrt überprüft werden.", "Alle der oben genannten sind wahr.",
      "Keines der oben genannten."], 2),
    ("120) Which of these is true about the use of the reflective triangles?",
     "120) Welche dieser Aussagen ist wahr über die Verwendung der Warndreiecke?",
     ["They should be set out within 10 minutes of stopping.",
      "They should be placed on a hill or curve for maximum visibility.", "All of the above are true.",
      "None of the above."], ["Sie sollten innerhalb von 10 Minuten nach dem Anhalten aufgestellt werden.",
                              "Sie sollten an einer Steigung oder Kurve für maximale Sichtbarkeit platziert werden.",
                              "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 2),
    ("121) Which of these is true about the coupling of a trailer?",
     "121) Welche dieser Aussagen ist wahr über die Kupplung eines Anhängers?",
     ["The fifth wheel should be checked for proper locking.",
      "The air lines and electrical cables must be connected properly.", "All of the above are true.",
      "None of the above."], ["Die Sattelkupplung sollte auf ordnungsgemäße Verriegelung überprüft werden.",
                              "Die Luftleitungen und Elektrokabel müssen richtig angeschlossen sein.",
                              "Alle der oben genannten sind wahr.", "Keines der oben genannten."], 2),
    ("122) Which of these is true about the vehicle registration?",
     "122) Welche dieser Aussagen ist wahr über die Fahrzeugregistrierung?",
     ["It must be carried in the vehicle.", "It must be current.", "All of the above are true.", "None of the above."],
     ["Sie muss im Fahrzeug mitgeführt werden.", "Sie muss aktuell sein.", "Alle der oben genannten sind wahr.",
      "Keines der oben genannten."], 2),
    ("123) Which of these is true about the vehicle dimensions?",
     "123) Welche dieser Aussagen ist wahr über die Fahrzeugabmessungen?",
     ["You must know the height and width of your vehicle.", "You must know the length of your vehicle and trailer.",
      "All of the above are true.", "None of the above."], ["Sie müssen die Höhe und Breite Ihres Fahrzeugs kennen.",
                                                            "Sie müssen die Länge Ihres Fahrzeugs und Anhängers kennen.",
                                                            "Alle der oben genannten sind wahr.",
                                                            "Keines der oben genannten."], 2),
    ("124) Which of these is true about the use of headlights?",
     "124) Welche dieser Aussagen ist wahr über die Verwendung von Scheinwerfern?",
     ["They should be used from sunset to sunrise.", "They should be used in poor weather.",
      "All of the above are true.", "None of the above."],
     ["Sie sollten von Sonnenuntergang bis Sonnenaufgang verwendet werden.",
      "Sie sollten bei schlechtem Wetter verwendet werden.", "Alle der oben genannten sind wahr.",
      "Keines der oben genannten."], 2),
    ("125) Which of these is true about the use of the horn?",
     "125) Welche dieser Aussagen ist wahr über die Verwendung der Hupe?",
     ["It should be used to avoid accidents.", "It should be used to alert others of your presence.",
      "All of the above are true.", "None of the above."], ["Sie sollte verwendet werden, um Unfälle zu vermeiden.",
                                                            "Sie sollte verwendet werden, um andere auf Ihre Anwesenheit aufmerksam zu machen.",
                                                            "Alle der oben genannten sind wahr.",
                                                            "Keines der oben genannten."], 2),
    ("126) For your safety, when setting out reflective triangles you should:",
     "126) Für Ihre Sicherheit, wenn Sie Warndreiecke aufstellen, sollten Sie:",
     ["Carry the triangle at your side.", "Hold the triangles between yourself and oncoming traffic.",
      "Keep them out of sight while you walk to the spots where you set them out.", "All of the above are true."],
     ["Das Dreieck an Ihrer Seite tragen.", "Die Dreiecke zwischen sich und dem entgegenkommenden Verkehr halten.",
      "Sie außer Sichtweite halten, während Sie zu den Stellen gehen, wo Sie sie aufstellen.",
      "Alle der oben genannten sind wahr."], 1),
    ("127) If you need to leave the road in a traffic emergency, you should:",
     "127) Wenn Sie die Straße in einem Verkehrsnotsfall verlassen müssen, sollten Sie:",
     ["Try to get all the wheels off the pavement.", "Brake hard as you leave the road.",
      "Avoid braking until your speed has dropped to about 20 mph.",
      "Avoid the shoulder because most shoulders will not support a large vehicle."],
     ["Versuchen, alle Räder von der Fahrbahn zu bekommen.", "Stark bremsen, wenn Sie die Straße verlassen.",
      "Bremsen vermeiden, bis Ihre Geschwindigkeit auf etwa 20 mph gesunken ist.",
      "Den Seitenstreifen meiden, da die meisten Seitenstreifen ein großes Fahrzeug nicht tragen."], 2)
]

# Start des zweisprachigen General Knowledge Quiz
if __name__ == "__main__":
    run_bilingual_quiz(quiz_fragen_general_knowledge, "CDL General Knowledge Test", "CDL Allgemeinwissen Test")